<?php

namespace Proxies\__CG__\Wbn\WebinaireBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Webi extends \Wbn\WebinaireBundle\Entity\Webi implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setDatecreation($datecreation)
    {
        $this->__load();
        return parent::setDatecreation($datecreation);
    }

    public function getDatecreation()
    {
        $this->__load();
        return parent::getDatecreation();
    }

    public function setTitrepage($titrepage)
    {
        $this->__load();
        return parent::setTitrepage($titrepage);
    }

    public function getTitrepage()
    {
        $this->__load();
        return parent::getTitrepage();
    }

    public function setMotclepage($motclepage)
    {
        $this->__load();
        return parent::setMotclepage($motclepage);
    }

    public function getMotclepage()
    {
        $this->__load();
        return parent::getMotclepage();
    }

    public function setDescriptionpage($descriptionpage)
    {
        $this->__load();
        return parent::setDescriptionpage($descriptionpage);
    }

    public function getDescriptionpage()
    {
        $this->__load();
        return parent::getDescriptionpage();
    }

    public function setTimezone($timezone)
    {
        $this->__load();
        return parent::setTimezone($timezone);
    }

    public function getTimezone()
    {
        $this->__load();
        return parent::getTimezone();
    }

    public function setPlannification($plannification)
    {
        $this->__load();
        return parent::setPlannification($plannification);
    }

    public function getPlannification()
    {
        $this->__load();
        return parent::getPlannification();
    }

    public function setActiverplannification($activerplannification)
    {
        $this->__load();
        return parent::setActiverplannification($activerplannification);
    }

    public function getActiverplannification()
    {
        $this->__load();
        return parent::getActiverplannification();
    }

    public function setNombredejouraafficher($nombredejouraafficher)
    {
        $this->__load();
        return parent::setNombredejouraafficher($nombredejouraafficher);
    }

    public function getNombredejouraafficher()
    {
        $this->__load();
        return parent::getNombredejouraafficher();
    }

    public function setNombresessionjour($nombresessionjour)
    {
        $this->__load();
        return parent::setNombresessionjour($nombresessionjour);
    }

    public function getNombresessionjour()
    {
        $this->__load();
        return parent::getNombresessionjour();
    }

    public function setHeuredessessions($heuredessessions)
    {
        $this->__load();
        return parent::setHeuredessessions($heuredessessions);
    }

    public function getHeuredessessions()
    {
        $this->__load();
        return parent::getHeuredessessions();
    }

    public function setSujetwebinaire($sujetwebinaire)
    {
        $this->__load();
        return parent::setSujetwebinaire($sujetwebinaire);
    }

    public function getSujetwebinaire()
    {
        $this->__load();
        return parent::getSujetwebinaire();
    }

    public function setNompresentateur($nompresentateur)
    {
        $this->__load();
        return parent::setNompresentateur($nompresentateur);
    }

    public function getNompresentateur()
    {
        $this->__load();
        return parent::getNompresentateur();
    }

    public function setImagepresentateur($imagepresentateur)
    {
        $this->__load();
        return parent::setImagepresentateur($imagepresentateur);
    }

    public function getImagepresentateur()
    {
        $this->__load();
        return parent::getImagepresentateur();
    }

    public function setTextheader($textheader)
    {
        $this->__load();
        return parent::setTextheader($textheader);
    }

    public function getTextheader()
    {
        $this->__load();
        return parent::getTextheader();
    }

    public function setEnablevideo($enablevideo)
    {
        $this->__load();
        return parent::setEnablevideo($enablevideo);
    }

    public function getEnablevideo()
    {
        $this->__load();
        return parent::getEnablevideo();
    }

    public function setActiveraffichagepresentateur($activeraffichagepresentateur)
    {
        $this->__load();
        return parent::setActiveraffichagepresentateur($activeraffichagepresentateur);
    }

    public function getActiveraffichagepresentateur()
    {
        $this->__load();
        return parent::getActiveraffichagepresentateur();
    }

    public function setActiveraffichagedescription($activeraffichagedescription)
    {
        $this->__load();
        return parent::setActiveraffichagedescription($activeraffichagedescription);
    }

    public function getActiveraffichagedescription()
    {
        $this->__load();
        return parent::getActiveraffichagedescription();
    }

    public function setDescriptionwebinaire($descriptionwebinaire)
    {
        $this->__load();
        return parent::setDescriptionwebinaire($descriptionwebinaire);
    }

    public function getDescriptionwebinaire()
    {
        $this->__load();
        return parent::getDescriptionwebinaire();
    }

    public function setUrlvideoremerciment($urlvideoremerciment)
    {
        $this->__load();
        return parent::setUrlvideoremerciment($urlvideoremerciment);
    }

    public function getUrlvideoremerciment()
    {
        $this->__load();
        return parent::getUrlvideoremerciment();
    }

    public function setAffichervideocomptearebour($affichervideocomptearebour)
    {
        $this->__load();
        return parent::setAffichervideocomptearebour($affichervideocomptearebour);
    }

    public function getAffichervideocomptearebour()
    {
        $this->__load();
        return parent::getAffichervideocomptearebour();
    }

    public function setUrlvideocomptearebour($urlvideocomptearebour)
    {
        $this->__load();
        return parent::setUrlvideocomptearebour($urlvideocomptearebour);
    }

    public function getUrlvideocomptearebour()
    {
        $this->__load();
        return parent::getUrlvideocomptearebour();
    }

    public function setUrlvideowebinaire($urlvideowebinaire)
    {
        $this->__load();
        return parent::setUrlvideowebinaire($urlvideowebinaire);
    }

    public function getUrlvideowebinaire()
    {
        $this->__load();
        return parent::getUrlvideowebinaire();
    }

    public function setDureevideo($dureevideo)
    {
        $this->__load();
        return parent::setDureevideo($dureevideo);
    }

    public function getDureevideo()
    {
        $this->__load();
        return parent::getDureevideo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'datecreation', 'titrepage', 'motclepage', 'descriptionpage', 'timezone', 'plannification', 'activerplannification', 'nombredejouraafficher', 'nombresessionjour', 'heuredessessions', 'sujetwebinaire', 'nompresentateur', 'imagepresentateur', 'textheader', 'enablevideo', 'activeraffichagepresentateur', 'activeraffichagedescription', 'descriptionwebinaire', 'urlvideoremerciment', 'affichervideocomptearebour', 'urlvideocomptearebour', 'urlvideowebinaire', 'dureevideo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}