<?php

namespace Wbn\WebinaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WebiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebiRepository extends EntityRepository
{
}
