parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: ''
    database_name: webinaire
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 458edc0590db980af9f95347879fa1714d119a34
    database_path: null
